import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/Component/SideBar/SideBar";
import NavBar from "@/Component/NavBar/NavBar";
import Footer from "@/Component/Footer/Footer";
import { Nunito } from "next/font/google";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  display: 'swap', // Better performance
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${nunito.variable}  antialiased`}>
        <SidebarProvider className="border border-red-600">
          <AppSidebar />

          <div className="w-full">
            <NavBar />
            <main style={{ minHeight: "calc(100vh - 110px)" }}>{children}</main>
            <Footer />
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
