import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import AppProvider from "@/AppProvider/AppProvider";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        
          <Toaster />
          <AppProvider>{children}</AppProvider>
        
      </body>
    </html>
  );
}
