// import type { Metadata } from "next";
// import "./globals.css";
// import { SidebarProvider } from "@/components/ui/sidebar";
// import { AppSidebar } from "@/Component/SideBar/SideBar";
// import NavBar from "@/Component/NavBar/NavBar";
// import Footer from "@/Component/Footer/Footer";
// import { Inter } from "next/font/google";

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
//   display: 'swap', // Better performance
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${inter.variable} antialiased`}>
//         <SidebarProvider className="border border-red-600">
//           <AppSidebar />
//           <div className="w-full">
//             <NavBar />
//             <main style={{ minHeight: "calc(100vh - 110px)" }}>{children}</main>
//             <Footer />
//           </div>
//         </SidebarProvider>
//       </body>
//     </html>
//   );
// }



import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}